language: r
dist: xenial
latex: true

branches:
  only:
    - master

cache:
  packages: yes
  directories:
    - $HOME/bin

env:
  global:
    secure: 820ce1dd1d7db8c8f424e17384f4d89a9ad2d366

script:
  - Rscript -e 'rmarkdown::render_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: public
  repo: ManifoldPreacher/manifoldpreacher.github.io
  target_branch: master
