name: "In Terra Aliena"
navbar:
    title: "In Terra Aliena"
    href: index.html
    left:
    - text: "Publications and Projects"
      href: publications_projects.html
    - text: "Teaching"
      href: teaching.html
    - text: "Articles"
      href: articles.html
  right:
    - icon: fa-envelope
      href: mailto:adriel_ong@zoho.com

output:
  html_document:
    theme: cosmo
    highlight: textmate
    include:
      after_body: _footer.html
      in_header: _header.html
    css: ../styles.css
    self_contained: false
